name: pg
channels:
  - gimli
  - conda-forge
dependencies:
  - python=3.10  # Python 3.10
  - pygimli>=1.5.0  # pygimli version 1.5.0 or higher
  - suitesparse=5  # suitesparse version 5
  - pandas
  - matplotlib
  - numpy
  - pyqt5
  - pip