# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 675)
        MainWindow.setMinimumSize(QtCore.QSize(870, 675))
        MainWindow.setMaximumSize(QtCore.QSize(870, 675))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#labelDropArea {\n"
"    background-color: #D3D3D3; \n"
"    border: 2px dashed white; \n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 881, 661))
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Australia))
        self.tabWidget.setObjectName("tabWidget")
        self.DataInputTab = QtWidgets.QWidget()
        self.DataInputTab.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Australia))
        self.DataInputTab.setObjectName("DataInputTab")
        self.textEditProcessedTxtPreview = QtWidgets.QTextEdit(self.DataInputTab)
        self.textEditProcessedTxtPreview.setGeometry(QtCore.QRect(40, 150, 411, 181))
        self.textEditProcessedTxtPreview.setObjectName("textEditProcessedTxtPreview")
        self.textEdit_4 = QtWidgets.QTextEdit(self.DataInputTab)
        self.textEdit_4.setGeometry(QtCore.QRect(40, 110, 291, 31))
        self.textEdit_4.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"}")
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButtonStartDataProcessing = QtWidgets.QPushButton(self.DataInputTab)
        self.pushButtonStartDataProcessing.setGeometry(QtCore.QRect(730, 530, 111, 41))
        self.pushButtonStartDataProcessing.setObjectName("pushButtonStartDataProcessing")
        self.textEdit = QtWidgets.QTextEdit(self.DataInputTab)
        self.textEdit.setGeometry(QtCore.QRect(40, 20, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.DataInputTab)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 60, 261, 41))
        self.textEdit_2.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButtonBrowserFiles = QtWidgets.QPushButton(self.DataInputTab)
        self.pushButtonBrowserFiles.setGeometry(QtCore.QRect(470, 290, 111, 41))
        self.pushButtonBrowserFiles.setObjectName("pushButtonBrowserFiles")
        self.XZcheckBox = QtWidgets.QCheckBox(self.DataInputTab)
        self.XZcheckBox.setGeometry(QtCore.QRect(470, 480, 131, 20))
        self.XZcheckBox.setTabletTracking(False)
        self.XZcheckBox.setChecked(True)
        self.XZcheckBox.setObjectName("XZcheckBox")
        self.textEditProcessedTempPreview = QtWidgets.QTextEdit(self.DataInputTab)
        self.textEditProcessedTempPreview.setGeometry(QtCore.QRect(40, 380, 411, 191))
        self.textEditProcessedTempPreview.setObjectName("textEditProcessedTempPreview")
        self.label_13 = QtWidgets.QLabel(self.DataInputTab)
        self.label_13.setGeometry(QtCore.QRect(530, 50, 321, 71))
        self.label_13.setObjectName("label_13")
        self.pushButtonBrowserTempFiles = QtWidgets.QPushButton(self.DataInputTab)
        self.pushButtonBrowserTempFiles.setGeometry(QtCore.QRect(470, 530, 111, 41))
        self.pushButtonBrowserTempFiles.setObjectName("pushButtonBrowserTempFiles")
        self.textEdit_7 = QtWidgets.QTextEdit(self.DataInputTab)
        self.textEdit_7.setGeometry(QtCore.QRect(40, 340, 291, 31))
        self.textEdit_7.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"}")
        self.textEdit_7.setObjectName("textEdit_7")
        self.pushButtonOpenTx0Dir = QtWidgets.QPushButton(self.DataInputTab)
        self.pushButtonOpenTx0Dir.setGeometry(QtCore.QRect(600, 290, 111, 41))
        self.pushButtonOpenTx0Dir.setObjectName("pushButtonOpenTx0Dir")
        self.pushButtonTempDir = QtWidgets.QPushButton(self.DataInputTab)
        self.pushButtonTempDir.setGeometry(QtCore.QRect(600, 530, 111, 41))
        self.pushButtonTempDir.setObjectName("pushButtonTempDir")
        self.tabWidget.addTab(self.DataInputTab, "")
        self.Inversion = QtWidgets.QWidget()
        self.Inversion.setObjectName("Inversion")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Inversion)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 851, 601))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.textEdit_9 = QtWidgets.QTextEdit(self.page_2)
        self.textEdit_9.setGeometry(QtCore.QRect(10, 20, 161, 31))
        self.textEdit_9.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"}")
        self.textEdit_9.setObjectName("textEdit_9")
        self.graphicsViewApparent = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsViewApparent.setGeometry(QtCore.QRect(100, 90, 651, 201))
        self.graphicsViewApparent.setObjectName("graphicsViewApparent")
        self.graphicsViewDepth = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsViewDepth.setGeometry(QtCore.QRect(100, 350, 651, 201))
        self.graphicsViewDepth.setObjectName("graphicsViewDepth")
        self.toolButton = QtWidgets.QToolButton(self.page_2)
        self.toolButton.setGeometry(QtCore.QRect(770, 560, 81, 22))
        self.toolButton.setObjectName("toolButton")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(360, 60, 111, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(370, 320, 111, 21))
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_2)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.formLayoutWidget = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 90, 160, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutXstart = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayoutXstart.setContentsMargins(0, 0, 0, 0)
        self.formLayoutXstart.setObjectName("formLayoutXstart")
        self.startXLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.startXLabel.setObjectName("startXLabel")
        self.formLayoutXstart.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.startXLabel)
        self.startXLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.startXLineEdit.setText("")
        self.startXLineEdit.setObjectName("startXLineEdit")
        self.formLayoutXstart.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startXLineEdit)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(210, 90, 160, 31))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayoutZstart = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayoutZstart.setContentsMargins(0, 0, 0, 0)
        self.formLayoutZstart.setObjectName("formLayoutZstart")
        self.startZLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.startZLabel.setObjectName("startZLabel")
        self.formLayoutZstart.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.startZLabel)
        self.startZLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.startZLineEdit.setObjectName("startZLineEdit")
        self.formLayoutZstart.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startZLineEdit)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 130, 160, 31))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayoutXend = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayoutXend.setContentsMargins(0, 0, 0, 0)
        self.formLayoutXend.setObjectName("formLayoutXend")
        self.endXLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.endXLabel.setObjectName("endXLabel")
        self.formLayoutXend.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.endXLabel)
        self.endXLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.endXLineEdit.setObjectName("endXLineEdit")
        self.formLayoutXend.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.endXLineEdit)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(210, 130, 160, 31))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayoutZend = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayoutZend.setContentsMargins(0, 0, 0, 0)
        self.formLayoutZend.setObjectName("formLayoutZend")
        self.endZLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.endZLabel.setObjectName("endZLabel")
        self.formLayoutZend.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.endZLabel)
        self.endZLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.endZLineEdit.setObjectName("endZLineEdit")
        self.formLayoutZend.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.endZLineEdit)
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(410, 89, 160, 71))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayoutQuality = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayoutQuality.setContentsMargins(0, 0, 0, 0)
        self.formLayoutQuality.setObjectName("formLayoutQuality")
        self.horizontalSlider = QtWidgets.QSlider(self.formLayoutWidget_5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.formLayoutQuality.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider)
        self.qualityLabel = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.qualityLabel.setObjectName("qualityLabel")
        self.formLayoutQuality.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.qualityLabel)
        self.qualityLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.qualityLineEdit.setObjectName("qualityLineEdit")
        self.formLayoutQuality.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.qualityLineEdit)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(600, 110, 160, 31))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayoutArea = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayoutArea.setContentsMargins(0, 0, 0, 0)
        self.formLayoutArea.setHorizontalSpacing(0)
        self.formLayoutArea.setObjectName("formLayoutArea")
        self.areaLabel = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.areaLabel.setObjectName("areaLabel")
        self.formLayoutArea.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.areaLabel)
        self.areaLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.areaLineEdit.setObjectName("areaLineEdit")
        self.formLayoutArea.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.areaLineEdit)
        self.textEdit_5 = QtWidgets.QTextEdit(self.page_1)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 30, 261, 31))
        self.textEdit_5.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"}")
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.page_1)
        self.textEdit_6.setGeometry(QtCore.QRect(20, 310, 351, 31))
        self.textEdit_6.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"}")
        self.textEdit_6.setObjectName("textEdit_6")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(20, 370, 160, 31))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.LambdaLayout = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.LambdaLayout.setContentsMargins(0, 0, 0, 0)
        self.LambdaLayout.setObjectName("LambdaLayout")
        self.LambdaLabel = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.LambdaLabel.setObjectName("LambdaLabel")
        self.LambdaLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LambdaLabel)
        self.LambdaLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LambdaLineEdit.setText("")
        self.LambdaLineEdit.setObjectName("LambdaLineEdit")
        self.LambdaLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LambdaLineEdit)
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(210, 370, 160, 31))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.LambdaLayoutIteration = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.LambdaLayoutIteration.setContentsMargins(0, 0, 0, 0)
        self.LambdaLayoutIteration.setObjectName("LambdaLayoutIteration")
        self.IterationLabel = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.IterationLabel.setObjectName("IterationLabel")
        self.LambdaLayoutIteration.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.IterationLabel)
        self.IterationLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.IterationLineEdit.setText("")
        self.IterationLineEdit.setObjectName("IterationLineEdit")
        self.LambdaLayoutIteration.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IterationLineEdit)
        self.formLayoutWidget_17 = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget_17.setGeometry(QtCore.QRect(400, 370, 160, 31))
        self.formLayoutWidget_17.setObjectName("formLayoutWidget_17")
        self.LambdaLayoutdPhi = QtWidgets.QFormLayout(self.formLayoutWidget_17)
        self.LambdaLayoutdPhi.setContentsMargins(0, 0, 0, 0)
        self.LambdaLayoutdPhi.setObjectName("LambdaLayoutdPhi")
        self.dPhiLabel = QtWidgets.QLabel(self.formLayoutWidget_17)
        self.dPhiLabel.setObjectName("dPhiLabel")
        self.LambdaLayoutdPhi.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dPhiLabel)
        self.dPhiLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_17)
        self.dPhiLineEdit.setText("")
        self.dPhiLineEdit.setObjectName("dPhiLineEdit")
        self.LambdaLayoutdPhi.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dPhiLineEdit)
        self.formLayoutWidget_18 = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget_18.setGeometry(QtCore.QRect(600, 370, 160, 31))
        self.formLayoutWidget_18.setObjectName("formLayoutWidget_18")
        self.LambdaLayoutIteration_4 = QtWidgets.QFormLayout(self.formLayoutWidget_18)
        self.LambdaLayoutIteration_4.setContentsMargins(0, 0, 0, 0)
        self.LambdaLayoutIteration_4.setObjectName("LambdaLayoutIteration_4")
        self.checkBox = QtWidgets.QCheckBox(self.formLayoutWidget_18)
        self.checkBox.setObjectName("checkBox")
        self.LambdaLayoutIteration_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.buttonBoxResetConfirmSave = QtWidgets.QDialogButtonBox(self.page_1)
        self.buttonBoxResetConfirmSave.setGeometry(QtCore.QRect(580, 550, 241, 24))
        self.buttonBoxResetConfirmSave.setStandardButtons(
                QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Reset | QtWidgets.QDialogButtonBox.Save
        )
        self.buttonBoxResetConfirmSave.setObjectName("buttonBoxResetConfirmSave")
        self.label_2 = QtWidgets.QLabel(self.page_1)
        self.label_2.setGeometry(QtCore.QRect(20, 430, 741, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_1)
        self.label_3.setGeometry(QtCore.QRect(20, 450, 741, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_1)
        self.label_4.setGeometry(QtCore.QRect(20, 470, 741, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_1)
        self.label_5.setGeometry(QtCore.QRect(20, 490, 741, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_1)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 741, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_1)
        self.label_7.setGeometry(QtCore.QRect(20, 200, 741, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_1)
        self.label_8.setGeometry(QtCore.QRect(20, 220, 741, 21))
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_1)
        self.tabWidget.addTab(self.Inversion, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_10.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.textEdit_10.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"}")
        self.textEdit_10.setObjectName("textEdit_10")
        self.listWidgetTxt = QtWidgets.QListWidget(self.tab_4)
        self.listWidgetTxt.setGeometry(QtCore.QRect(20, 80, 261, 221))
        self.listWidgetTxt.setObjectName("listWidgetTxt")
        self.listWidgetImg = QtWidgets.QListWidget(self.tab_4)
        self.listWidgetImg.setGeometry(QtCore.QRect(430, 80, 261, 481))
        self.listWidgetImg.setObjectName("listWidgetImg")
        self.pushButtonTxt = QtWidgets.QPushButton(self.tab_4)
        self.pushButtonTxt.setGeometry(QtCore.QRect(300, 80, 91, 24))
        self.pushButtonTxt.setObjectName("pushButtonTxt")
        self.pushButtonImg = QtWidgets.QPushButton(self.tab_4)
        self.pushButtonImg.setGeometry(QtCore.QRect(710, 80, 91, 24))
        self.pushButtonImg.setObjectName("pushButtonImg")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(20, 50, 111, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(430, 50, 111, 21))
        self.label_12.setObjectName("label_12")
        self.pushButtonCache = QtWidgets.QPushButton(self.tab_4)
        self.pushButtonCache.setGeometry(QtCore.QRect(760, 550, 91, 24))
        self.pushButtonCache.setObjectName("pushButtonCache")
        self.listWidgetTxt_2 = QtWidgets.QListWidget(self.tab_4)
        self.listWidgetTxt_2.setGeometry(QtCore.QRect(20, 330, 261, 221))
        self.listWidgetTxt_2.setObjectName("listWidgetTxt_2")
        self.pushButtonTxt_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButtonTxt_2.setGeometry(QtCore.QRect(300, 330, 91, 24))
        self.pushButtonTxt_2.setObjectName("pushButtonTxt_2")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInstall_Dependency = QtWidgets.QAction(MainWindow)
        self.actionInstall_Dependency.setObjectName("actionInstall_Dependency")
        self.actionActivate_conda_environment = QtWidgets.QAction(MainWindow)
        self.actionActivate_conda_environment.setObjectName("actionActivate_conda_environment")
        self.actionDeactivate_conda_environment = QtWidgets.QAction(MainWindow)
        self.actionDeactivate_conda_environment.setObjectName("actionDeactivate_conda_environment")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionInstall_Dependency)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionActivate_conda_environment)
        self.menuHelp.addAction(self.actionDeactivate_conda_environment)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt; color:#838383;\">ERT Raw file directory</span></p></body></html>"))
        self.pushButtonStartDataProcessing.setText(_translate("MainWindow", "Start"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Arial Narrow\'; font-size:14pt; font-weight:700; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:18pt; font-weight:400;\">Soil Condition Mapping</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:14pt; color:#838383;\">Process, Mapping, Display</span></p></body></html>"))
        self.pushButtonBrowserFiles.setText(_translate("MainWindow", "Browser"))
        self.XZcheckBox.setText(_translate("MainWindow", "XZ Axis Check Box"))
        self.label_13.setText(_translate("MainWindow", "1st Click Browser or drop to select your Raw ERT data\n"
"2nd Click Start or drop to select your Temprature data\n"
" 3rd: press start \n"
" optional: check box to omit XZ axis "))
        self.pushButtonBrowserTempFiles.setText(_translate("MainWindow", "Browser"))
        self.textEdit_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt; color:#838383;\">Tempareture file directory</span></p></body></html>"))
        self.pushButtonOpenTx0Dir.setText(_translate("MainWindow", "Open..."))
        self.pushButtonTempDir.setText(_translate("MainWindow", "Open..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataInputTab), _translate("MainWindow", "Data Input"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt; color:#838383;\">Inversion Output</span></p></body></html>"))
        self.toolButton.setText(_translate("MainWindow", "Save To"))
        self.label_9.setText(_translate("MainWindow", "Apparent Resistivity"))
        self.label_10.setText(_translate("MainWindow", "Resistivity in Depth"))
        self.startXLabel.setText(_translate("MainWindow", "Start X"))
        self.startZLabel.setText(_translate("MainWindow", "Start Z"))
        self.endXLabel.setText(_translate("MainWindow", "End X"))
        self.endZLabel.setText(_translate("MainWindow", "End Z"))
        self.qualityLabel.setText(_translate("MainWindow", "Quality"))
        self.areaLabel.setText(_translate("MainWindow", "Area"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt; color:#838383;\">Mesh and Geometry Settings</span></p></body></html>"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt; color:#838383;\">Inversion Parameters Settings</span></p></body></html>"))
        self.LambdaLabel.setText(_translate("MainWindow", "Lambda"))
        self.IterationLabel.setText(_translate("MainWindow", "Max Iterations"))
        self.dPhiLabel.setText(_translate("MainWindow", "dPhi"))
        self.checkBox.setText(_translate("MainWindow", "Robust Data"))
        self.label_2.setText(_translate("MainWindow", "Lambda: Controls the balance between data fitting and model smoothness."))
        self.label_3.setText(_translate("MainWindow", "Max Iterations: Sets the maximum number of iterations for the inversion process."))
        self.label_4.setText(_translate("MainWindow", "dPhi: Determines the acceptable reduction in data misfit during inversion."))
        self.label_5.setText(_translate("MainWindow", "Robust Data: Enable to reduce the impact of outliers in the data."))
        self.label_6.setText(_translate("MainWindow", "Start/ End (X/Z Coordinates): Defines the starting X and Z coordinates for the survey area boundary."))
        self.label_7.setText(_translate("MainWindow", "Quality: Sets the mesh quality, influencing the smoothness and resolution of the model."))
        self.label_8.setText(_translate("MainWindow", "Area: Determines the maximum cell size in the mesh, affecting the level of detail in the model."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Inversion), _translate("MainWindow", "Inversion"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt; color:#838383;\">Temporary files</span></p></body></html>"))
        self.pushButtonTxt.setText(_translate("MainWindow", "Delete selected"))
        self.pushButtonImg.setText(_translate("MainWindow", "Delete selected"))
        self.label_11.setText(_translate("MainWindow", "Resistivity Files"))
        self.label_12.setText(_translate("MainWindow", "Image Files"))
        self.pushButtonCache.setText(_translate("MainWindow", "Delete Cache"))
        self.pushButtonTxt_2.setText(_translate("MainWindow", "Delete selected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Cached Files"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Config"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionInstall_Dependency.setText(_translate("MainWindow", "Install Dependency..."))
        self.actionActivate_conda_environment.setText(_translate("MainWindow", "Activate conda environment"))
        self.actionDeactivate_conda_environment.setText(_translate("MainWindow", "Deactivate conda environment"))
