name: Python Package using Conda

on:
  push:
    branches:
      - dev
      - main
      - executable
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      max-parallel: 3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false

      - name: Create Conda environment
        run: conda env create --file environment.yml

      - name: Verify Python version in Conda environment
        run: conda run -n pg python --version

      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Test with pytest in Conda environment for UI (data processing and I/O)
        run: xvfb-run -a conda run -n pg python ui_logic_test.py

      - name: Test with pytest in Conda environment for Data Inversion
        run: conda run -n pg python DataInversion/ERT_Main.py

      - name: Test with pytest in Conda environment for Water Content
        run: conda run -n pg python WaterContent/Water_test.py